package io.stereov.singularity.database.core.util

import io.stereov.singularity.translate.model.Translatable
import org.springframework.data.mongodb.core.query.Criteria
import org.springframework.data.mongodb.core.query.Query
import org.springframework.data.mongodb.core.query.isEqualTo
import java.util.*
import kotlin.reflect.KProperty

/**
 * A builder to create and manage a list of [Criteria] objects for querying.
 * This class provides utility methods to add conditions to the criteria list,
 * effectively constructing queries based on various constraints.
 *
 * @property criteriaList A mutable list of [Criteria] objects used to build query conditions.
 */
class CriteriaBuilder(
    val criteriaList: MutableList<Criteria> = mutableListOf()
) {

    constructor(criteria: Criteria): this(mutableListOf(criteria))

    /**
     * Builds and returns a combined [Criteria] object from the list of criteria in the builder.
     * If the criteria list is empty, returns `null`.
     *
     * @return A [Criteria] object combining all criteria in the list, or `null` if the list is empty.
     */
    fun build(): Criteria? {
        return if (criteriaList.isNotEmpty()) {
            Criteria().andOperator(*criteriaList.toTypedArray())
        } else null
    }

    /**
     * Creates a new [Query] object based on the combined [Criteria] generated by the `build` method.
     * If the `build` method returns `null`, an empty [Query] object is returned instead.
     *
     * @return A [Query] object representing the combined criteria or an empty [Query] if no criteria are defined.
     */
    fun query(): Query {
        return build()?.let { Query(it) } ?: Query()
    }

    private fun getFieldName(field: String, locale: Locale? = null) = when(locale) {
        null -> field
        else -> "${Translatable<*>::translations.name}.$locale.$field"
    }

    /**
     * Adds a regex-based search condition to the criteria list for the specified field,
     * matching it against a given substring.
     *
     * @param field The name of the field to apply the search condition on.
     * @param substring The substring to match within the field. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun fieldContains(field: String, substring: String?, locale: Locale? = null): CriteriaBuilder {
        if (substring == null) return this

        val actualField = getFieldName(field, locale)
        val regexPattern = ".*${Regex.escape(substring)}.*"
        criteriaList.add(Criteria.where(actualField).regex(regexPattern, "i"))

        return this
    }

    /**
     * Adds a regex-based search condition to the criteria list for the specified field,
     * matching it against a given substring.
     *
     * @param field The property representing the field to apply the search condition on.
     * @param substring The substring to match within the field. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun fieldContains(field: KProperty<*>, substring: String?, locale: Locale? = null): CriteriaBuilder {
        return fieldContains(field.name, substring, locale)
    }

    /**
     * Adds comparison criteria to the criteria list based on the specified field and values for less than or equal,
     * greater than or equal, and equality.
     *
     * @param field The name of the field to apply the comparison criteria on.
     * @param lte A value representing the upper bound (less than or equal to) for the field. If `null`, this condition is not added.
     * @param gte A value representing the lower bound (greater than or equal to) for the field. If `null`, this condition is not added.
     * @param equals A value for strict equality comparison on the field. If `null`, this condition is not added. Defaults to `null`.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun compare(field: String, lte: Comparable<*>?, gte: Comparable<*>?, equals: Comparable<*>? = null, locale: Locale? = null): CriteriaBuilder {
        val actualField = getFieldName(field, locale)

        lte?.let { criteriaList.add(Criteria.where(actualField).lte(lte)) }
        gte?.let { criteriaList.add(Criteria.where(actualField).gte(gte)) }
        equals?.let { criteriaList.add(Criteria.where(actualField).isEqualTo(equals))}

        return this
    }

    /**
     * Adds comparison criteria to the criteria list based on the specified field and values for less than or equal,
     * greater than or equal, and equality.
     *
     * @param field The property representing the field to apply the comparison criteria on.
     * @param lte A value representing the upper bound (less than or equal to) for the field. If `null`, this condition is not added.
     * @param gte A value representing the lower bound (greater than or equal to) for the field. If `null`, this condition is not added.
     * @param equals A value for strict equality comparison on the field. If `null`, this condition is not added. Defaults to `null`.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun compare(field: KProperty<*>, lte: Comparable<*>?, gte: Comparable<*>?, equals: Comparable<*>? = null, locale: Locale? = null): CriteriaBuilder {
        return compare(field.name, lte, gte, equals, locale)
    }

    /**
     * Adds an equality condition to the criteria list for the specified field, matching it against the provided value.
     *
     * @param field The name of the field to apply the equality condition on.
     * @param value The value to compare the field against. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun isEqualTo(field: String, value: Any?, locale: Locale? = null): CriteriaBuilder {
        if (value == null) return this

        val actualField = getFieldName(field, locale)
        criteriaList.add(Criteria.where(actualField).isEqualTo(value))

        return this
    }

    /**
     * Adds an equality condition to the criteria list for the specified field, matching it against the provided value.
     *
     * @param field The property representing the field to apply the equality condition on.
     * @param value The value to compare the field against. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun isEqualTo(field: KProperty<*>, value: Any?, locale: Locale? = null): CriteriaBuilder {
        return isEqualTo(field.name, value, locale)
    }

    /**
     * Adds an 'in' condition to the criteria list for the specified field,
     * checking if its value is within the provided collection.
     *
     * @param field The name of the field to apply the 'in' condition on.
     * @param collection The collection of values to check against. If `null` or empty, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun isIn(field: String, collection: Collection<*>?, locale: Locale? = null): CriteriaBuilder {
        if (collection.isNullOrEmpty()) return this
        criteriaList.add(Criteria.where(getFieldName(field, locale)).`in`(collection))

        return this
    }

    /**
     * Adds an 'in' condition to the criteria list for the specified field,
     * checking if its value is within the provided collection.
     *
     * @param field The property representing the field to apply the 'in' condition on.
     * @param collection The collection of values to check against. If `null` or empty, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun isIn(field: KProperty<*>, collection: Collection<*>?, locale: Locale? = null): CriteriaBuilder {
        return isIn(field.name, collection, locale)
    }

    /**
     * Adds an equality condition to the criteria list for the specified field, matching it against the provided value.
     *
     * @param field The name of the field to apply the condition on.
     * @param value The value to compare the field against. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun hasElement(field: String, value: Any?, locale: Locale? = null): CriteriaBuilder {
        if (value == null) return this
        criteriaList.add(Criteria.where(getFieldName(field, locale)).`is`(value))

        return this
    }

    /**
     * Adds a condition to the criteria list to check if the specified field contains the given value.
     *
     * @param field The property representing the field to check for the value.
     * @param value The value to check if it exists within the field. If `null`, no condition is added.
     * @param locale An optional locale used to resolve a localized field name. Defaults to `null`.
     * @return This [CriteriaBuilder] instance for method chaining.
     */
    fun hasElement(field: KProperty<*>, value: Any?, locale: Locale? = null): CriteriaBuilder {
        return hasElement(field.name, value, locale)
    }

    /**
     * Builds and adds a criteria that checks the existence of any of the specified values
     * in a database or collection.
     * Optional prefix and locale can be provided to customize
     * field naming before applying the criteria.
     *
     * @param values A collection of values to check for existence. If null or empty, no criteria is added.
     * @param prefix An optional string prefix to prepend to the field names. Defaults to null.
     * @param locale An optional locale to adjust field name formatting based on locale-specific rules. Defaults to null.
     * @return Returns the updated CriteriaBuilder instance with the newly added criteria.
     */
    fun existsAny(values: Collection<*>?, prefix: String? = null, locale: Locale? = null): CriteriaBuilder {
        if (values.isNullOrEmpty()) return this
        val actualPrefix = prefix?.let { it.removeSuffix(".") + "." }
        val criteria = Criteria().orOperator(
            *values.map { value ->
                val actualField = getFieldName("${actualPrefix ?: ""}$value", locale)
                Criteria.where(actualField).exists(true)
            }.toTypedArray()
        )

        criteriaList.add(criteria)
        return this
    }

    /**
     * Generates a CriteriaBuilder instance by verifying the existence of any elements in the given collection.
     *
     * @param values The collection of values to evaluate. Can be null.
     * @param prefix An optional property used as a prefix for evaluation. Can be null.
     * @param locale The locale to be used for processing, if applicable. Can be null.
     * @return The created CriteriaBuilder instance based on the provided parameters.
     */
    fun existsAny(values: Collection<*>?, prefix: KProperty<*>? = null, locale: Locale? = null): CriteriaBuilder {
        return existsAny(values, prefix?.name, locale)
    }

    /**
     * Adds the specified criteria to the list and returns the CriteriaBuilder instance.
     *
     * @param criteria The criteria object to be added to the criteria list.
     * @return The CriteriaBuilder instance for further modifications.
     */
    fun add(criteria: Criteria): CriteriaBuilder {
        criteriaList.add(criteria)
        return this
    }

}
