apiVersion: v1
kind: Secret
metadata:
  name: stereov-io-singularity-secrets
type: Opaque
stringData:
  ROOT_EMAIL: ""
  ROOT_PASSWORD: ""
  MONGO_DB_USERNAME: ""
  MONGO_DB_PASSWORD: ""
  REDIS_PASSWORD: ""
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  BITWARDEN_ACCESS_TOKEN: ""
  BITWARDEN_ORGANIZATION_ID: ""
  BITWARDEN_PROJECT_ID: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
