#server:
#  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_DATABASE_NAME}?authSource=admin&tls=${MONGO_DB_SSL_ENABLED:false}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000ms}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  devtools:
    restart:
      enabled: ${DEV_MODE:false}
      additional-paths: src/main

logging:
  level:
    io.stereov: ${LOG_LEVEL:DEBUG}

baseline:
  app:
    name: TestApplication
    base-url: ${BACKEND_BASE_URL}
    secure: ${SECURE:false}
  mail:
    enable: ${ENABLE_EMAIL_VERIFICATION:true}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    email: ${MAIL_EMAIL}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    transport-protocol: ${MAIL_TRANSPORT_PROTOCOL:smtp}
    smtp-auth: ${MAIL_SMTP_AUTH:true}
    smtp-starttls: ${MAIL_SMTP_STARTTLS:true}
    debug: ${MAIL_DEBUG:false}
    verification-expiration: ${MAIL_VERIFICATION_EXPIRATION:900}
    verification-send-cooldown: ${MAIL_VERIFICATION_SEND_COOLDOWN:60}
    password-reset-expiration: ${MAIL_PASSWORD_RESET_EXPIRATION:900}
    password-reset-send-cooldown: ${MAIL_PASSWORD_RESET_SEND_COOLDOWN:60}
    ui-verification-path: ${EMAIL_VERIFICATION_PATH}
  security:
    encryption:
      secret-key: ${SECRET_KEY}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expires-in: ${JWT_EXPIRATION:900}
    rate-limit:
      ip-limit: ${IP_RATE_LIMIT_MINUTE:200}
      ip-time-window: 1
      user-limit: ${ACCOUNT_RATE_LIMIT_MINUTE:100}
      user-time-window: 1
    login-attempt-limit:
      ip-limit: 10
      ip-time-window: 15
    two-factor:
      recovery-code-length: 20
  ui:
    base-url: ${FRONTEND_BASE_URL}
