services:
  dev_mongo:
    image: mongodb/mongodb-community-server:latest@sha256:9cdf9e0f2c029b6ad3903401632419f6e54eaf07735dc56b5329e61e6ccf702a
    container_name: dev_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: singularity
      MONGO_INITDB_ROOT_PASSWORD: singularity
    volumes:
      - dev_mongo_data:/data/db
  dev_redis:
    image: redis:latest@sha256:009cc37796fbdbe1b631b4cc0582bed167e5e403ed8bcd06f77eb6cb5aeb6f93
    container_name: dev_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "singularity"]
volumes:
  dev_mongo_data:
