services:
  dev_mongo:
    image: mongodb/mongodb-community-server:latest@sha256:a1290462f9fc6a5b10cdb7c7156a0685de76bdca5c4174f8fd9b126bf164df5f
    container_name: dev_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: singularity
      MONGO_INITDB_ROOT_PASSWORD: singularity
    volumes:
      - dev_mongo_data:/data/db
  dev_redis:
    image: redis:latest@sha256:4d25e2fe601f7ffaeb4437cb6ced3518bc36edf34ebe98863c80836943d94529
    container_name: dev_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "singularity"]
volumes:
  dev_mongo_data:
