services:
  dev_mongo:
    image: mongodb/mongodb-community-server:latest@sha256:8ecd67579e4c59295c476dc03e2325601e252acae79c52c21555130962a6d31f
    container_name: dev_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: singularity
      MONGO_INITDB_ROOT_PASSWORD: singularity
    volumes:
      - dev_mongo_data:/data/db
  dev_redis:
    image: redis:latest@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    container_name: dev_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "singularity"]
volumes:
  dev_mongo_data:
