name: content - Sync to mirror repo

on:
  push:
    branches:
      - main
    paths:
      - '../../../libs/content'
      - 'sync.yml'
    tags:
      - 'v*'

env:
  MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Split subtree
        run: |
          git subtree split --prefix=libs/content -b sync-content

      - name: Add mirror remote and push branch
        run: |
          git remote add mirror git@github.com:antistereov/singularity-content.git
          git push -f mirror sync-content:main

      - name: Push tags if matching
        run: |
          TAGS=$(git tag -l || true)
          for TAG in $TAGS; do
            git push mirror $TAG || echo "Failed to push tag $TAG"
          done
