import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/singularity-api",
    },
    {
      type: "category",
      label: "Authentication",
      link: {
        type: "generated-index",
        title: "Authentication",
        slug: "/category/api/authentication",
      },
      items: [
        {
          type: "doc",
          id: "api/register",
          label: "Register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/login",
          label: "Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/logout",
          label: "Logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/refresh-access-token",
          label: "Refresh Access Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/step-up",
          label: "Step-Up",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-authentication-status",
          label: "Get Authentication Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/send-password-reset-email",
          label: "Send Password Reset Email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reset-password",
          label: "Reset Password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-remaining-password-reset-cooldown",
          label: "Get Remaining Password Reset CooldownActive",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/send-email-verification-email",
          label: "Send Email Verification Email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/verify-email",
          label: "Verify Email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-remaining-email-verification-cooldown",
          label: "Get Remaining Email Verification CooldownActive",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Two-Factor Authentication",
      link: {
        type: "generated-index",
        title: "Two-Factor Authentication",
        slug: "/category/api/two-factor-authentication",
      },
      items: [
        {
          type: "doc",
          id: "api/complete-login",
          label: "Complete Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/complete-step-up",
          label: "Complete Step-Up",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/change-preferred-two-factor-method",
          label: "Change Preferred 2FA Method",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-totp-setup-details",
          label: "Get TOTP Setup Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/enable-totp-as-two-factor-method",
          label: "Enable TOTP as 2FA Method",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-totp-as-two-factor-method",
          label: "Disable TOTP as 2FA Method",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/recover-from-totp",
          label: "Recover From TOTP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/send-email-two-factor-code",
          label: "Send Email 2FA Code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/enable-email-as-two-factor-method",
          label: "Enable Email as 2FA Method",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-email-as-two-factor-method",
          label: "Disable Email as 2FA Method",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-remaining-email-two-factor-cooldown",
          label: "Get Remaining Email 2FA Cooldown",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "OAuth2",
      link: {
        type: "generated-index",
        title: "OAuth2",
        slug: "/category/api/o-auth-2",
      },
      items: [
        {
          type: "doc",
          id: "api/get-identity-providers",
          label: "Get Identity Providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-identity-provider",
          label: "Delete Identity Provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/add-password-authentication",
          label: "Add Password Authentication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-o-auth-2-provider-connection-token",
          label: "Generate OAuth2ProviderConnectionToken",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Profile Management",
      link: {
        type: "generated-index",
        title: "Profile Management",
        slug: "/category/api/profile-management",
      },
      items: [
        {
          type: "doc",
          id: "api/get-authorized-principal",
          label: "Get Principal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-authorized-user",
          label: "Update Principal",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-authorized-principal",
          label: "Delete Principal",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/change-email-of-authorized-user",
          label: "Change Email",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/change-password-of-authorized-user",
          label: "Change Password",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/set-avatar-of-authorized-user",
          label: "Update Avatar",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-avatar-of-authorized-user",
          label: "Delete Avatar",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Sessions",
      link: {
        type: "generated-index",
        title: "Sessions",
        slug: "/category/api/sessions",
      },
      items: [
        {
          type: "doc",
          id: "api/get-active-sessions",
          label: "Get Active Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-all-sessions",
          label: "Delete All Sessions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/delete-session",
          label: "Delete Session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/generate-session-token",
          label: "Generate SessionToken",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Managing Users",
      link: {
        type: "generated-index",
        title: "Managing Users",
        slug: "/category/api/managing-users",
      },
      items: [
        {
          type: "doc",
          id: "api/get-user-by-id",
          label: "Get User By ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-user-by-id",
          label: "Delete User By ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-users",
          label: "Get Users",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Roles",
      link: {
        type: "generated-index",
        title: "Roles",
        slug: "/category/api/roles",
      },
      items: [
        {
          type: "doc",
          id: "api/create-guest-account",
          label: "Create Guest Principal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/convert-guest-to-user",
          label: "Convert Guest To User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/grant-admin-permissions",
          label: "Grant Admin Permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/revoke-admin-permissions",
          label: "Revoke Admin Permissions",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Groups",
      link: {
        type: "generated-index",
        title: "Groups",
        slug: "/category/api/groups",
      },
      items: [
        {
          type: "doc",
          id: "api/get-groups",
          label: "Get Groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-group",
          label: "Create Group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-group-by-key",
          label: "Get Group By Key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-group",
          label: "Update Group",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-group",
          label: "Delete Group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/add-member-to-group",
          label: "Add Member to Group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-member-from-group",
          label: "Remove Member from Group",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Security",
      link: {
        type: "generated-index",
        title: "Security",
        slug: "/category/api/security",
      },
      items: [
        {
          type: "doc",
          id: "api/rotate-secret-keys",
          label: "Trigger Secret Rotation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-secret-key-rotation-status",
          label: "Get Secret Rotation Status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Content Management",
      link: {
        type: "generated-index",
        title: "Content Management",
        slug: "/category/api/content-management",
      },
      items: [
        {
          type: "doc",
          id: "api/get-content-object-access-details",
          label: "Get Access Details of Content Objects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-content-object-access",
          label: "Update Access of Content Objects",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-content-object-owner",
          label: "Update Owner of Content Object ",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-content-object-trusted-state",
          label: "Update Trusted State of Content Object ",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-content-object-by-key",
          label: "Delete Content Object",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Articles",
      link: {
        type: "generated-index",
        title: "Articles",
        slug: "/category/api/articles",
      },
      items: [
        {
          type: "doc",
          id: "api/get-articles",
          label: "Get Articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-article",
          label: "Create Article",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-article-by-key",
          label: "Get Article By Key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-article",
          label: "Update Article",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/update-article-state",
          label: "Update Article State",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-article-image",
          label: "Update Article Image",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-content-object-access-details",
          label: "Get Access Details of Content Objects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-content-object-access",
          label: "Update Access of Content Objects",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-content-object-owner",
          label: "Update Owner of Content Object ",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-content-object-trusted-state",
          label: "Update Trusted State of Content Object ",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-content-object-by-key",
          label: "Delete Content Object",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Invitations",
      link: {
        type: "generated-index",
        title: "Invitations",
        slug: "/category/api/invitations",
      },
      items: [
        {
          type: "doc",
          id: "api/invite-user-to-content-object",
          label: "Invite User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/accept-invitation-to-content-object",
          label: "Accept Invitation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-invitation-to-content-object-by-id",
          label: "Delete Invitation",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Tags",
      link: {
        type: "generated-index",
        title: "Tags",
        slug: "/category/api/tags",
      },
      items: [
        {
          type: "doc",
          id: "api/get-tags",
          label: "Get Tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-tag",
          label: "Create Tag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-tag-by-key",
          label: "Get Tag By Key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-tag",
          label: "Delete Tag",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/update-tag",
          label: "Update Tag",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Local File Storage",
      link: {
        type: "generated-index",
        title: "Local File Storage",
        slug: "/category/api/local-file-storage",
      },
      items: [
        {
          type: "doc",
          id: "api/serve-file",
          label: "Get File from Local File Storage",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/changeprincipalrequest",
          label: "ChangePrincipalRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contentaccessdetailsresponse",
          label: "ContentAccessDetailsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filemetadataresponse",
          label: "FileMetadataResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/filerenditionresponse",
          label: "FileRenditionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/guest",
          label: "Guest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/klogger",
          label: "KLogger",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/objectid",
          label: "ObjectId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/userresponse",
          label: "UserResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changepasswordrequest",
          label: "ChangePasswordRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeemailrequest",
          label: "ChangeEmailRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeemailresponse",
          label: "ChangeEmailResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/grouptranslation",
          label: "GroupTranslation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updategrouprequest",
          label: "UpdateGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/groupresponse",
          label: "GroupResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contentresponseobject",
          label: "ContentResponseObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateownerrequest",
          label: "UpdateOwnerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatecontentaccessrequest",
          label: "UpdateContentAccessRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changearticlestaterequest",
          label: "ChangeArticleStateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/articlecolors",
          label: "ArticleColors",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fullarticleresponse",
          label: "FullArticleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tagresponse",
          label: "TagResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/useroverviewresponse",
          label: "UserOverviewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessioninforequest",
          label: "SessionInfoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/generatesessiontokenresponse",
          label: "GenerateSessionTokenResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addpasswordauthenticationrequest",
          label: "AddPasswordAuthenticationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/oauth-2-providerconnectiontokenresponse",
          label: "OAuth2ProviderConnectionTokenResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/oauth-2-providerconnectionrequest",
          label: "OAuth2ProviderConnectionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/successresponse",
          label: "SuccessResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createguestrequest",
          label: "CreateGuestRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/city",
          label: "City",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/continent",
          label: "Continent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/country",
          label: "Country",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createguestresponse",
          label: "CreateGuestResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/geolocationresponse",
          label: "GeolocationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/converttouserrequest",
          label: "ConvertToUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/converttouserresponse",
          label: "ConvertToUserResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/creategrouprequest",
          label: "CreateGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/inviteusertocontentrequest",
          label: "InviteUserToContentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/extendedcontentaccessdetailsresponse",
          label: "ExtendedContentAccessDetailsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/invitationresponse",
          label: "InvitationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usercontentaccessdetails",
          label: "UserContentAccessDetails",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/acceptinvitationtocontentrequest",
          label: "AcceptInvitationToContentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createtagrequest",
          label: "CreateTagRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createarticlerequest",
          label: "CreateArticleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stepuprequest",
          label: "StepUpRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stepupresponse",
          label: "StepUpResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/registeruserrequest",
          label: "RegisterUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/refreshtokenresponse",
          label: "RefreshTokenResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/resetpasswordrequest",
          label: "ResetPasswordRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sendpasswordresetrequest",
          label: "SendPasswordResetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sendemailresponse",
          label: "SendEmailResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/loginrequest",
          label: "LoginRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/loginresponse",
          label: "LoginResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/twofactorsetupresponse",
          label: "TwoFactorSetupResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/twofactorverifysetuprequest",
          label: "TwoFactorVerifySetupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/twofactorrecoveryresponse",
          label: "TwoFactorRecoveryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/totprecoveryrequest",
          label: "TotpRecoveryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/completestepuprequest",
          label: "CompleteStepUpRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changepreferredtwofactormethodrequest",
          label: "ChangePreferredTwoFactorMethodRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/completeloginrequest",
          label: "CompleteLoginRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/enableemailtwofactormethodrequest",
          label: "EnableEmailTwoFactorMethodRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatetagrequest",
          label: "UpdateTagRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatearticlerequest",
          label: "UpdateArticleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageuseroverviewresponse",
          label: "PageUserOverviewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pageableobject",
          label: "PageableObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sortobject",
          label: "SortObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/locationinfo",
          label: "LocationInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessioninforesponse",
          label: "SessionInfoResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/identityproviderresponse",
          label: "IdentityProviderResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rotationinformation",
          label: "RotationInformation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rotationstatusresponse",
          label: "RotationStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/singularityexception",
          label: "SingularityException",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pagegroupresponse",
          label: "PageGroupResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pagetagresponse",
          label: "PageTagResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/articleoverviewresponse",
          label: "ArticleOverviewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pagearticleoverviewresponse",
          label: "PageArticleOverviewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/authenticationstatusresponse",
          label: "AuthenticationStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/mailcooldownresponse",
          label: "MailCooldownResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/databuffer",
          label: "DataBuffer",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
