name: Release and Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
  MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release_and_deploy:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew build -x test

      - name: Run Tests
        run: |
          ./gradlew test

      - name: Publish
        run: |
          ./gradlew publish

      - name: Release and Deploy
        run: |
          ./gradlew jreleaserFullRelease
