name: Release and Deploy

on:
  push:
    tags:
      - 'v*'

env:
  MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
  MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  release_and_deploy:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build and Test
      - name: Build with Gradle
        run: |
          ./gradlew assemble
      - name: Run Tests
        run: |
          ./gradlew test

      # Checking versions
      - name: Verify version numbers
        id: gradle_version
        run: |
          VERSION=$(./gradlew checkVersion --quiet)
          echo "Gradle Project Version: $VERSION"
          TAG_VERSION=${{ github.ref_name }}
          echo "Git Tag Version: $TAG_VERSION"
          
          if [[ "$TAG_VERSION" != "v$VERSION" ]]; then
              echo "❌ Version mismatch! Gradle version ($VERSION) does not match Git tag ($TAG_VERSION)"
              exit 1
          fi
          echo "✅ Versions match. Proceeding with release."


      # Publish
      - name: Publish
        run: |
          ./gradlew publish

      - name: Release and Deploy
        run: |
          ./gradlew jreleaserFullRelease

      - name: Commit Changelog
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add CHANGELOG.md
          git commit -m "docs(changelog): update changelog for ${{ github.event.release.tag_name }}"
          git push
          
